name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git
      run: |
        git config --global user.name "casaterraneo"
        git config --global user.email "casa.terraneo@gmail.com"      

    - name: Merge main into production
      run: |
        git checkout production
        git merge main --no-ff --commit -m "Merge branch 'main' into production"
        git push origin production
