name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Commit changes
      run: |
        git add .
        git commit -m "Automated commit from main to production"
        git push origin main --force
