name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git
      run: |
        git config --global user.name "casaterraneo"
        git config --global user.email "casa.terraneo@gmail.com"      

    - name: Estrazione modifiche dal ramo main
      run:  git fetch origin main

    - name: Unione nel ramo production
      run:  git merge origin/main

    - name: Esecuzione di test automatici (facoltativo)
        # Inserire qui i comandi per eseguire i test

    - name: Generazione del commit
      run:  git commit -m "Integrazione automatica modifiche dal ramo main"

    - name: Inoltro al ramo production
        git push origin HEAD:+productione
